language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"

install:
    # update aptitude
    - sudo apt-get update -y

    # install aptitude packages
    - LDFLAGS=-lm sudo aptitude install -y $(< requirements)

    # weird travis-ci python paths
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/pymodules/python2.7/
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/pyshared/python2.7/
    - export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/site-packages/

    # install python requirements
    - pip install -r test_requirements.txt --use-mirrors

    # verify both requirements were met
    - INSTALLDIR=$(python -c "import os; import thumbor; print(os.path.dirname(thumbor.__file__))")

script:
    # weird travis-ci python paths
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/pymodules/python2.7/
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/pyshared/python2.7/
    - export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/site-packages/

    # finally run tests
    - make ci_test

